"""Immutable value snapshots of canonical batch-runtime records."""

from app.service.judgehost.batch.model import (
    CaseRecord,
    ExecutionBatchRecord,
    ExecutionBatchRow,
    JudgehostCaseRow,
)


def batch_snapshot(batch: ExecutionBatchRecord) -> ExecutionBatchRow:
    return ExecutionBatchRow(
        batch_id=batch.batch_id,
        verification_program_id=batch.verification_program_id,
        execution_signature=batch.execution_signature,
        task_kind=batch.task_kind,
        verification_id=batch.verification_id,
        job_id=batch.job_id,
        compile_key=batch.compile_key,
        contest_id=batch.contest_id,
        mode=batch.mode,
        source_name=batch.source_name,
        compile_hash=batch.compile_hash,
        run_hash=batch.run_hash,
        compare_hash=batch.compare_hash,
        source_hash=batch.source_hash,
        compile_config_json=batch.compile_config_json,
        run_config_json=batch.run_config_json,
        compare_config_json=batch.compare_config_json,
        expected_behavior=batch.expected_behavior,
        verification_source=batch.verification_source,
        bypass_case_result_cache=batch.bypass_case_result_cache,
        compile_success=batch.compile_success,
        compile_state=batch.compile_state,
        materialization_state=batch.materialization_state,
        service_class=batch.service_class,
        compile_output_b64=batch.compile_output_b64 or "",
        compile_metadata_b64=batch.compile_metadata_b64 or "",
        debug_text=batch.debug_text,
        failure_runresult=batch.failure_runresult,
        failure_text=batch.failure_text,
        status=batch.status,
        created_at=batch.created_at,
        updated_at=batch.updated_at,
        completed_at=batch.completed_at or "",
    )


def case_snapshot(case: CaseRecord) -> JudgehostCaseRow:
    result = case.result
    return JudgehostCaseRow(
        id=case.id,
        batch_id=case.batch_id,
        task_id=case.task_id,
        verification_task_id=case.verification_task_id,
        run_id=case.run_id,
        test_name=case.test_name,
        ordinal=case.ordinal,
        scope_sequence=case.scope_sequence,
        testcase_id=case.testcase_id,
        testcase_hash=case.testcase_hash,
        testcase_input_hash=case.testcase_input_hash,
        testcase_answer_hash=case.testcase_answer_hash,
        input_ref=case.input_ref,
        answer_ref=case.answer_ref,
        status=case.status,
        lease_owner=case.lease_owner,
        cancel_requested=case.cancel_requested,
        runresult="" if result is None else result.runresult,
        runtime_sec=None if result is None else result.runtime_sec,
        cpu_sec=None if result is None else result.cpu_sec,
        wall_sec=None if result is None else result.wall_sec,
        memory_kb=None if result is None else result.memory_kb,
        output_run_ref="" if result is None else result.output_run_ref,
        output_error_ref="" if result is None else result.output_error_ref,
        output_system_ref="" if result is None else result.output_system_ref,
        output_diff_ref="" if result is None else result.output_diff_ref,
        metadata_ref="" if result is None else result.metadata_ref,
        compare_metadata_ref="" if result is None else result.compare_metadata_ref,
        team_message_ref="" if result is None else result.team_message_ref,
        score_text="" if result is None else result.score_text,
        debug_text=case.debug_text,
        completion_acknowledged=case.completion_acknowledged,
        last_callback_hostname=case.last_callback_hostname,
        created_at=case.created_at,
        updated_at=case.updated_at,
    )
