from fastapi.responses import HTMLResponse

from app.impl.preview.preview import (
    preview_page,
    preview_run,
    preview_save,
    preview_status,
    statement_tex_source,
    statement_compile_asset_upload,
    statement_attachment_upload,
    statement_language_add,
    statement_language_delete,
    statement_attachment_delete,
    statement_compile_asset_delete,
    statement_examples_template_save,
    statement_examples_template_toggle,
    statement_templates_reset,
)
from app.route.problem_scoped_router import ProblemScopedRouter

router = ProblemScopedRouter()

router.add_api_route(
    "/problems/{problem:path}/preview",
    preview_page,
    methods=["GET"],
    response_class=HTMLResponse,
)
router.add_api_route(
    "/problems/{problem:path}/preview/run",
    preview_run,
    methods=["POST"],
)
router.add_api_route(
    "/problems/{problem:path}/preview/status",
    preview_status,
    methods=["GET"],
)
router.add_api_route(
    "/problems/{problem:path}/statement/source.tex",
    statement_tex_source,
    methods=["GET"],
)
router.add_api_route(
    "/problems/{problem:path}/preview/save",
    preview_save,
    methods=["POST"],
)
router.add_api_route(
    "/problems/{problem:path}/statement/assets/upload",
    statement_compile_asset_upload,
    methods=["POST"],
)
router.add_api_route(
    "/problems/{problem:path}/statement/assets/delete",
    statement_compile_asset_delete,
    methods=["POST"],
)
router.add_api_route(
    "/problems/{problem:path}/statement/attachments/upload",
    statement_attachment_upload,
    methods=["POST"],
)
router.add_api_route(
    "/problems/{problem:path}/statement/attachments/delete",
    statement_attachment_delete,
    methods=["POST"],
)
router.add_api_route(
    "/problems/{problem:path}/statement/languages/add",
    statement_language_add,
    methods=["POST"],
)
router.add_api_route(
    "/problems/{problem:path}/statement/languages/delete",
    statement_language_delete,
    methods=["POST"],
)
router.add_api_route(
    "/problems/{problem:path}/statement/templates/reset",
    statement_templates_reset,
    methods=["POST"],
)
router.add_api_route(
    "/problems/{problem:path}/statement/examples-template/toggle",
    statement_examples_template_toggle,
    methods=["POST"],
)
router.add_api_route(
    "/problems/{problem:path}/statement/examples-template/save",
    statement_examples_template_save,
    methods=["POST"],
)
