"""Canonical names for authored and rendered Contest statement files."""


CONTEST_STATEMENT_SHARED_SCOPE = "_shared"
CONTEST_STATEMENT_TEMPLATE_NAME = "statements.ftl"
CONTEST_STATEMENT_OUTPUT_NAME = "statements.tex"
CONTEST_STATEMENT_STYLE_NAME = "olymp.sty"

CONTEST_STATEMENT_LANGUAGE_DEFAULT_FILES = (
    CONTEST_STATEMENT_TEMPLATE_NAME,
    CONTEST_STATEMENT_STYLE_NAME,
)
CONTEST_STATEMENT_SHARED_PROTECTED_FILES = (
    CONTEST_STATEMENT_TEMPLATE_NAME,
    CONTEST_STATEMENT_OUTPUT_NAME,
    CONTEST_STATEMENT_STYLE_NAME,
)
