from __future__ import annotations

from app.runtime_value import RuntimeValues, build_runtime_values

TOOLCHAIN_CPP_COMPILER: str = "g++"
TOOLCHAIN_PYTHON_EXECUTABLE: str = "python3"
TOOLCHAIN_JAVA_COMPILER: str = "javac"
TOOLCHAIN_CPP_CXXFLAGS: tuple[str, ...] = ("-O2", "-std=gnu++20", "-pipe", "-static", "-DDOMJUDGE")
TOOLCHAIN_INCLUDE_RE = None
TOOLCHAIN_JAVA_MAIN_CLASS_RE = None
TOOLCHAIN_JAVA_JAVAC_FLAGS: tuple[str, ...] = (
    "-Xms16m",
    "-Xmx256m",
    "-XX:MaxMetaspaceSize=64m",
    "-XX:CompressedClassSpaceSize=32m",
)
TOOLCHAIN_JAVA_RUNTIME_FLAGS: tuple[str, ...] = (
    "-XX:+UseSerialGC",
    "-XX:TieredStopAtLevel=1",
    "-XX:ActiveProcessorCount=1",
    "-Xss256k",
    "-XX:-UseCompressedClassPointers",
)
TOOLCHAIN_JAVA_RUNTIME_DEFAULT_HEAP_MB = 256
TOOLCHAIN_JAVA_RUNTIME_MIN_HEAP_MB = 64
TOOLCHAIN_JAVA_RUNTIME_INITIAL_HEAP_MB = 16


def apply_runtime_values(values: RuntimeValues) -> None:
    global TOOLCHAIN_CPP_COMPILER
    global TOOLCHAIN_PYTHON_EXECUTABLE
    global TOOLCHAIN_JAVA_COMPILER
    global TOOLCHAIN_CPP_CXXFLAGS
    global TOOLCHAIN_INCLUDE_RE
    global TOOLCHAIN_JAVA_MAIN_CLASS_RE
    global TOOLCHAIN_JAVA_JAVAC_FLAGS
    global TOOLCHAIN_JAVA_RUNTIME_FLAGS
    global TOOLCHAIN_JAVA_RUNTIME_DEFAULT_HEAP_MB
    global TOOLCHAIN_JAVA_RUNTIME_MIN_HEAP_MB
    global TOOLCHAIN_JAVA_RUNTIME_INITIAL_HEAP_MB

    TOOLCHAIN_CPP_COMPILER = str(values.TOOLCHAIN_CPP_COMPILER)
    TOOLCHAIN_PYTHON_EXECUTABLE = str(values.TOOLCHAIN_PYTHON_EXECUTABLE)
    TOOLCHAIN_JAVA_COMPILER = str(values.TOOLCHAIN_JAVA_COMPILER)
    TOOLCHAIN_CPP_CXXFLAGS = tuple(str(x) for x in values.TOOLCHAIN_CPP_CXXFLAGS)
    TOOLCHAIN_INCLUDE_RE = values.TOOLCHAIN_INCLUDE_RE
    TOOLCHAIN_JAVA_MAIN_CLASS_RE = values.TOOLCHAIN_JAVA_MAIN_CLASS_RE
    TOOLCHAIN_JAVA_JAVAC_FLAGS = tuple(str(x) for x in values.TOOLCHAIN_JAVA_JAVAC_FLAGS)
    TOOLCHAIN_JAVA_RUNTIME_FLAGS = tuple(str(x) for x in values.TOOLCHAIN_JAVA_RUNTIME_FLAGS)
    TOOLCHAIN_JAVA_RUNTIME_DEFAULT_HEAP_MB = int(values.TOOLCHAIN_JAVA_RUNTIME_DEFAULT_HEAP_MB)
    TOOLCHAIN_JAVA_RUNTIME_MIN_HEAP_MB = int(values.TOOLCHAIN_JAVA_RUNTIME_MIN_HEAP_MB)
    TOOLCHAIN_JAVA_RUNTIME_INITIAL_HEAP_MB = int(values.TOOLCHAIN_JAVA_RUNTIME_INITIAL_HEAP_MB)


apply_runtime_values(build_runtime_values())
