from collections.abc import Iterable
from typing import Generic, TypeVar

_T = TypeVar("_T")


class SortedList(Generic[_T]):
    def __init__(self, iterable: Iterable[_T] = ...) -> None: ...
    def add(self, value: _T) -> None: ...
    def remove(self, value: _T) -> None: ...
    def clear(self) -> None: ...
    def __getitem__(self, index: int) -> _T: ...
    def __len__(self) -> int: ...
